name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone site source repository
      uses: actions/checkout@v2

    - name: Clone site output repository into '_site'
      uses: actions/checkout@v2
      with:
        name: Site
        repository: eddiejessup/eddiejessup.github.io
        path: '_site'
        token: ${{ secrets.GITHUBTOKEN }}

    - name: Set up Haskell tools
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Clear out existing site files and site cache
      run: |
        rm -r _cache _site/*.html _site/css _site/images _site/posts

    - name: Build site
      run: |
        cabal new-run . -- build

    - name: Commit site changes
      working-directory: _site
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "Update from CI"

    - name: Push site changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        directory: _site
        repository: eddiejessup/eddiejessup.github.io
